### ISSUE TITLE
Show real matched offers in swiper

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#11]
Show real matched offers at demand detail view in swiper

**Comment by TIIUNDER** [comment]
This seems to work now? Can we close the issue?

**Comment by stephanlindauer** [comment]
lets leave it open. i need to add logiv for fav and dismiss and simply tapping on it. will work on that tomorrow.

**Comment by TIIUNDER** [comment]
OK, I created a new issue for fav here https://github.com/neeedo/neeedo-android/issues/63

Stefan would like to make a screencast tomorrow for presentation, so, swiping should work.
I will try to implement layout.

**Comment by TIIUNDER** [comment]
I made some changes for the single view layouts, also for the swiper layout. Please check it and adjust if necessary

**Comment by stephanlindauer** [comment]
all done
