### ISSUE TITLE
German Translation file

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#22]
Create translations string file and add first German translations

**Comment by stephanlindauer** [comment]
@TIIUNDER @GammaG before i get started please check the views etc for strings that arent referenced in the strings file

**Comment by stephanlindauer** [comment]
@TIIUNDER will you first work on the german strings and then i'll translate or can you send me the notes on wording we decided on today?

**Comment by stephanlindauer** [comment]
@TIIUNDER @GammaG also we need one person for double checking everything in english and one for german. my smartphone is set to english so i could check english.

**Comment by GammaG** [comment]
placed all into strings.xml I could find.

**Comment by TIIUNDER** [comment]
I will add English strings, at the end we can create the german strings version. I also will upload my notes from yesterday (German wording). There are still some views open, I will change some things (for example forms) Also: testing is no problem, you can easily switch the languages in emulator using the custom locale app.

**Comment by TIIUNDER** [comment]
Wording notes: https://dl.dropboxusercontent.com/u/17564871/neeedo_wording_german.pdf

**Comment by TIIUNDER** [comment]
Layout and stings file should be ready, we can start with translation

**Comment by stephanlindauer** [comment]
done
