### ISSUE TITLE
cant favourite from list offers

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#29]
![fav](https://cloud.githubusercontent.com/assets/1323145/8813484/2bccdf4e-3004-11e5-8de5-95749590e237.png)

**Comment by stephanlindauer** [comment]
please also reference bugfix commit

**Comment by GammaG** [comment]
Well that's means you aren't logged in and the action you make does require this, I would say we change the error message to "Please login to do that." or something in that kind.

Also how about we don't display the actions if the user isn't logged in?

**Comment by GammaG** [comment]
done
