### ISSUE TITLE
Demand use distance out of Map

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#3]
At the moment new Demand saves the distance out of the form, not out of the map.

**Comment by stephanlindauer** [comment]
@TIIUNDER just to make sure: distance is irrelevant for new offers?

**Comment by stephanlindauer** [comment]
@TIIUNDER dont answer. stupid question. ^^

**Comment by stephanlindauer** [comment]
what unit is expected? km? m?

**Comment by stephanlindauer** [comment]
@TIIUNDER please doublecheck if it works as expected and close ticket

**Comment by TIIUNDER** [comment]
Ok, it works
