### ISSUE TITLE
unknown error when successfully creating new demand

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#32]
![bug tag](https://cloud.githubusercontent.com/assets/1323145/8814418/849f7692-300c-11e5-9a75-a14b055dba97.png)

**Comment by GammaG** [comment]
Well you removed 
     etDistance.setText(String.valueOf(currentDemand.getDistance()));
in  EditDemandFragment which causes the update process to send a body without the distance attribute. 
Which does not match the requirements of the api https://github.com/neeedo/neeedo-api#update-demand for the update process, causing a http 400. That  is displayed as "unkown error" due this isn't an error any user should see.  

When unsure what to put in the Object look in the api doku what attributes it is required to have.

To fix this I can either send a default distance, or we recreate it in the code.

**Comment by GammaG** [comment]
default distance 10 to entity class added. closed
