### ISSUE TITLE
mark unread conversations

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#33]
![image](https://cloud.githubusercontent.com/assets/1323145/8814641/18129f74-300f-11e5-9fdd-ef24f37e5415.png)

**Comment by TIIUNDER** [comment]
You mean something like a "new" badge or marking it bold?

**Comment by TIIUNDER** [comment]
https://github.com/neeedo/neeedo-android/issues/21

**Comment by stephanlindauer** [comment]
yeap bold text would make sense

**Comment by TIIUNDER** [comment]
Done

![screenshot_2015-07-24-23 09 51-1](https://cloud.githubusercontent.com/assets/1225378/8884710/1c6a65f6-3259-11e5-977a-0756bfe00de5.png)

**Comment by GammaG** [comment]
looks nice
