### ISSUE TITLE
show avatar with starting letter in nickname, last send message and maybe a topic

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#34]
like in the gmail app http://cdn.arstechnica.net/wp-content/uploads/2013/06/2013-06-07-14.14.30.png

**Comment by GammaG** [comment]
Yeah we can make that, I guess you mean in the message fragment ?

**Comment by TIIUNDER** [comment]
https://github.com/neeedo/neeedo-android/issues/21

**Comment by TIIUNDER** [comment]
done :)
