### ISSUE TITLE
unread message count behaves weirdly. goes up step by step within seconds and flickers sometimes.

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#35]

**Comment by GammaG** [comment]
Ah maybe I know what you mean, if you open the conversation the counter decreases ? That's because on every successfull "set read" call to the api the message counter lowers by one and does a refresh. If we don't make that refresh can take up to 30 seconds.

**Comment by stephanlindauer** [comment]
i can show you on tuesday

**Comment by stephanlindauer** [comment]
oops

**Comment by GammaG** [comment]
does work now
