### ISSUE TITLE
keep user that are not logged in from doing things. overlay?

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#36]

**Comment by GammaG** [comment]
I think it's a good idear

**Comment by TIIUNDER** [comment]
We had the login activity open up in the past. But this wasn't nice. What's the alternative?

**Comment by GammaG** [comment]
currently "You aren\'t allowed to do that. Please login before proceed." is displayed or just no content is displayed. In SingleOfferView I made all buttons visible = "GONE" when there is no active login.

**Comment by GammaG** [comment]
due there is a redirect to the main fragment on the logout button, illegal actions shouldn't be possible to start. Because nearly every fragment loads all of its content while starting up and based upon the logged in user.

**Comment by TIIUNDER** [comment]
Maybe it's the easiest way to force every user, which starts the app, to login

**Comment by stephanlindauer** [comment]
agreed. everything else would take up too much time now.

**Comment by TIIUNDER** [comment]
@GammaG maybe you can add this?

**Comment by GammaG** [comment]
I will take a look

**Comment by GammaG** [comment]
maybe we should talk about this tuesday, I have an idear how to solve this, but I don't like it from usabillity viewpoint.

**Comment by GammaG** [comment]
several changes were made
