### ISSUE TITLE
Delete local cached product at deletion out of list

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#41]
If I delete a Demand or Offer, I can see the item still in the list after redirection. I have to reload the list.

Is it possible to delete the local stored offer or demand out of the list?

**Comment by GammaG** [comment]
shouldn't be a problem, just some new functions needs to be implemented. Did this already for offers

**Comment by GammaG** [comment]
remove now works with local cache and sets a state for the listeview to use cache instead of server data

**Comment by TIIUNDER** [comment]
When I try to delete an Offer or Demand it seams to get deleted in Sphere. But it stays in list and also reloading the list doesn't change that. Also it's not possible to deleting it anymore, because I get a 404 error (of course).

**Comment by TIIUNDER** [comment]
Same problem for updated offers/demands. The old offer/demand stays in list, new offer/demand is just added.

**Comment by GammaG** [comment]
mh I will take a look, but don't know why it works on my device. Will test this in emulator

**Comment by TIIUNDER** [comment]
It behaves really strange. Sometimes it works, sometimes I have to refresh the list and sometimes refreshing the list also doesn't help. Please check this screencast https://dl.dropboxusercontent.com/u/17564871/android_delete_bugs.mp4

**Comment by GammaG** [comment]
ok I will try to reproduce

**Comment by GammaG** [comment]
issue has been fixed
