### ISSUE TITLE
Use current location for map

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#42]
If we have time for this, we can try to implement the current location for the map. It would be nice to have focus on the current (maybe last known location?) on the location map chooser.

**Comment by stephanlindauer** [comment]
I'd say we have two different features here.
first: when map is first loaded center on last known location. -> done
second: have a button that starts the location listener and use the first location update with decent accuracy and set the location on the map. -> works so far but i want more visual feedback for the time its trying to find the location.

**Comment by stephanlindauer** [comment]
@TIIUNDER please check if you like how it works. i'll close this for now.
