### ISSUE TITLE
When removing a second offer after first success remove app crashes 

### ISSUE THREAD

**Issue by GammaG** [neeedo/neeedo-android#43]
Process: neeedo.imimaprx.htw.de.neeedo, PID: 22824
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131427497, class android.widget.ListView) with Adapter(class neeedo.imimaprx.htw.de.neeedo.fragments.adapters.ListProductsArrayAdapter)]

**Comment by TIIUNDER** [comment]
I can't reproduce this. Also it seams, that the list doesn't get refreshed after deleting an offer/demand.

**Comment by GammaG** [comment]
mh not on my device, I will test this on emulator

**Comment by stephanlindauer** [comment]
@GammaG probably because things are time sensitive? *suprise

**Comment by TIIUNDER** [comment]
The whole deleting stuff from https://github.com/neeedo/neeedo-android/issues/41 is not working like expected. Please find a clean solution for that, I think this problem will also disappear after that.

**Comment by GammaG** [comment]
closed because duplicate
