### ISSUE TITLE
Delete image

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#45]
It would be nice to delete images of offers

**Comment by GammaG** [comment]
there is no api option for that. The only thing you can do is create an offer draft remove the image from the list and sent that via update.

**Comment by stephanlindauer** [comment]
this will be done in the backend if images are not referenced anymore. nothing for us to worry about.

**Comment by TIIUNDER** [comment]
No, I would like to be able to remove an image out o the image list of an offer. So, we need a button for each image, which removes the reference.

**Comment by stephanlindauer** [comment]
aaaah. sorry! ;)

**Comment by stephanlindauer** [comment]
ok. done. should work properly as soon as #47 is resolved.
