### ISSUE TITLE
editing images in edit offer view creates a new one

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#47]

**Comment by TIIUNDER** [comment]
Because of that issue: https://github.com/neeedo/neeedo-android/issues/41

**Comment by GammaG** [comment]
ok I will take a look

**Comment by stephanlindauer** [comment]
@GammaG dont. i am actually already working on it.

**Comment by stephanlindauer** [comment]
@GammaG ah no. wrong issue. do take a look i am working on something else.

**Comment by GammaG** [comment]
Was a cache problem, old one wasn't removed due update. Should work now
