### ISSUE TITLE
After second delete in ListOffersFragment, adapterviews behaviour is inconsitent, due it does not recreate the list from cache.

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#50]
i cant even get a stacktrace from logcat. the whole thing exits.

**Comment by TIIUNDER** [comment]
Yes, once I got an ArrayIndexOutOfBounce, other times it just behaves strange. I think this is linked to this issue https://github.com/neeedo/neeedo-android/issues/41

**Comment by GammaG** [comment]
ListOffersFragment, seems not to reload after second delete action. That causes the list to be inconsitent due the element is removed from the list and api, but not from the adapterview in ListOffersFragment. After second delete onActivityCreated was never called.

**Comment by TIIUNDER** [comment]
moved it from onActivityCreated to onViewStateRestored, this gets called every time. But still it doesn't work 100% perfect.

**Comment by TIIUNDER** [comment]
Ok, I found and removed the redirect which is redirecting to the lists. Now you can add an event which redirects after deleting operation is finished.

**Comment by TIIUNDER** [comment]
I added the subscribers, you can see it at this commit: https://github.com/neeedo/neeedo-android/commit/7a1d7dbcb2b47b32675accdbc41ca433b211882b

Please check if this works for you and check if you have still to improve some code

**Comment by TIIUNDER** [comment]
And please keep in mind: The API also works asynchronous. So I think it's good to remove the local cached item too. So I would keep this change, you did before. @GammaG

**Comment by GammaG** [comment]
yep I will keep that. But seems to work now
