### ISSUE TITLE
Show location in detail views

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#52]
Is there an easy way to display locations in the single view? I would like to see where I can get my matched offers.

**Comment by stephanlindauer** [comment]
do you mean inside the swipeable element?

**Comment by TIIUNDER** [comment]
I think it's enough to see it in the detail view, for example if I open it out of my favorites list. Btw: is it possible to get to the detail view from the swiper (maybe by clicking the swipable card)?

**Comment by stephanlindauer** [comment]
of the matched offer? yep.

**Comment by TIIUNDER** [comment]
Yes, this would be perfect. After that we should able to see the location (maybe address, city or map - depends which is easier to implement) in the detail view

**Comment by stephanlindauer** [comment]
done
