### ISSUE TITLE
Correct not found message for offer/demand deletion

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#55]
Please add a correct error message, if you try to delete an offer/demand, which does not exist anymore (error 404). At the moment you get "An unknown error occured". This should be something like "The offer/demand does not exist anymore" or something like this.

Easy way to reproduce: Launch the app and start the list for demands/offers. Delete an offer/demand in the webapp. Delete the same offer/demand in app, you will get an 404 error and sea the unknown error message.

**Comment by GammaG** [comment]
yeah I will add this.

**Comment by GammaG** [comment]
I will use "Your requested resource is not available anymore." as message.

**Comment by GammaG** [comment]
Is added
