### ISSUE TITLE
"new" in messages is not displayed, when reciving a new message

### ISSUE THREAD

**Issue by GammaG** [neeedo/neeedo-android#58]
I just tested this with sascha und the "new" sighn wasn't shown.
Do you check the "hasNewMessages" in user entity?  

![2015-07-25 09 42 46](https://cloud.githubusercontent.com/assets/2648086/8888921/d34fdd1e-32c2-11e5-894d-21555d754d1b.png)

**Comment by TIIUNDER** [comment]
Yes, I'm calling the hasNewMessage getter. Maybe it doesn't work if this fragment is already open. Where do I have to notify the list to have changes?

**Comment by GammaG** [comment]
@Subscribe
    public void getUsers(UserMessageContactsLoadedEvent userMessageContactsLoadedEvent) 
in MessageFragment

**Comment by GammaG** [comment]
wasn't able to reproduce
