### ISSUE TITLE
own messages should be on the right. others on the left. like in all messaging apps.

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#61]
![image](https://cloud.githubusercontent.com/assets/1323145/8889574/b468b570-32df-11e5-841f-e085c45fa54b.png)

**Comment by stephanlindauer** [comment]
whatsapp for example 
![image](https://cloud.githubusercontent.com/assets/1323145/8889577/e3765c50-32df-11e5-924c-8447f7de35ad.png)

**Comment by TIIUNDER** [comment]
Ooops, you are right. I will fix this ;-)

**Comment by TIIUNDER** [comment]
done
