### ISSUE TITLE
OpenStreet map not displayed on some devices

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#62]
On some devices (emulators), the map of the location chooser is not displayed:

For example:
- Emulator Nexus 4
- API Level 19 (Google)

![screenshot_2015-07-25-17 16 40-1](https://cloud.githubusercontent.com/assets/1225378/8890035/0d6bd650-32f1-11e5-955b-f3b3195a3a80.png)

Same problem occured at testing from Stefan.

**Comment by stephanlindauer** [comment]
but we are only talking about emulators here?

**Comment by TIIUNDER** [comment]
Fixed issue by adding a SD card to the emulator (OSM needs external storage, of course)
