### ISSUE TITLE
Refresh messages list?

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#67]
Is it possible to refresh the messages list for getting some kind of chat feeling?

**Comment by GammaG** [comment]
mh bad we need the info when to reload and we don't get that very well. See like I do for the message counter

**Comment by GammaG** [comment]
we just could refresh the messages by timer again.

**Comment by GammaG** [comment]
How about some gesture like "drag it down" to reload like facebook messenger does.

**Comment by TIIUNDER** [comment]
That's not that easy to implement. Is it possible to check it again every 30 seconds?

**Comment by GammaG** [comment]
Well yes, but it will cause a lot of traffic and I'm unsure if it's worth that trouble.

**Comment by GammaG** [comment]
will not be implemented
