### ISSUE TITLE
Favorite Offer(s) displayed in my offers list

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#68]
If I go to the favorites list and I have favorites there and after that visit my offers list, the favorites are added to the offers list. This should not happen.

![screenshot_2015-07-26-02 10 39-1](https://cloud.githubusercontent.com/assets/1225378/8891901/ced1fb04-333b-11e5-8352-e8d7f50b725b.png)

You can also check this screencast: https://dl.dropboxusercontent.com/u/17564871/android_fav_offer_bugs.mp4

**Comment by GammaG** [comment]
oh ok I will take a look

**Comment by GammaG** [comment]
shouldn't happen again

**Comment by TIIUNDER** [comment]
This still happens. I removed a favorite from list and now it is in the offers list again.

![screenshot_2015-07-27-11 58 30-1](https://cloud.githubusercontent.com/assets/1225378/8903259/f0a36a62-3456-11e5-9059-c7aeba3b828d.png)

**Comment by TIIUNDER** [comment]
Sorry, I checked it again. Now it works.
