### ISSUE TITLE
Messages from user "Neeedo" will get a redirect to the SingleOfferView

### ISSUE THREAD

**Issue by GammaG** [neeedo/neeedo-android#7]

**Comment by TIIUNDER** [comment]
The Neeedo user has the ID "Neeedo"
![screenshot_2015-07-21-10 46 50-1](https://cloud.githubusercontent.com/assets/1225378/8796554/d5ce247c-2f95-11e5-988c-cdad10bab5dd.png)

**Comment by GammaG** [comment]
thanks

**Comment by GammaG** [comment]
new changes here, just show "you have a new match" and on click redirect to singleOfferview

**Comment by GammaG** [comment]
please someone with message from "Neeedo" user test this

**Comment by TIIUNDER** [comment]
works now
