### ISSUE TITLE
When, following favorite to singleview the "star" still is uncollored, even through it is for sure in favorites 

### ISSUE THREAD

**Issue by GammaG** [neeedo/neeedo-android#71]
I just saw it does know that it is a favorite. But it is unclear for the user because own would think the star would be colored out then. 
And I don't think a dialog is needed there ^^ just remove it. The user will see if it was wrong and add it again.

**Comment by GammaG** [comment]
I would say we use first methode and ignore the other cases, the api does not add them twice

**Comment by TIIUNDER** [comment]
I will exchange them, colored = favorite, uncolored = no favorite (like webapp)

**Comment by TIIUNDER** [comment]
I think the dialog is needed, because if you un-fav an item, you have to find it again. So it's better to warn the user

**Comment by GammaG** [comment]
Might be, but the dialog does not redirect you, doesn't it? So the user still can add it again.

**Comment by TIIUNDER** [comment]
icons switched

**Comment by TIIUNDER** [comment]
I don't know, why it redirects after removing a favorite into the offer list. I will check that.

**Comment by TIIUNDER** [comment]
OK, the redirect happens, because the DeleteEvent asynctask is called. This event posts an event, which causes a redirect to the offers list, because this should happen when I delete the offer. So, if we want to remove this redirect we have to rewrite the event and/or asynctask

**Comment by GammaG** [comment]
changed it to FavoriteRemoveFinishedEvent, you now have to change how it reacts @TIIUNDER

**Comment by TIIUNDER** [comment]
removed confirm dialog, button change handled by event subscribers

**Comment by GammaG** [comment]
very nice
