### ISSUE TITLE
Double tapping the map makes the app crash sometimes

### ISSUE THREAD

**Issue by MeiSign** [neeedo/neeedo-android#72]
When you open the location view while creating an offer the app crashes sometimes when you double tap the map. Error log says:

```
 07-26 14:18:00.660  10452-10452/neeedo.imimaprx.htw.de.neeedo W/art﹕ Suspending all threads took: 23.020ms
 07-26 14:18:00.661  10452-10452/neeedo.imimaprx.htw.de.neeedo E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 262156 byte allocation with 227991 free bytes and 222KB until OOM"
 07-26 14:18:00.661  10452-10452/neeedo.imimaprx.htw.de.neeedo W/System.err﹕ 8417 [main] ERROR org.osmdroid.tileprovider.MapTileProviderBase - OutOfMemoryError rescaling cache
 07-26 14:18:00.673  10452-10548/neeedo.imimaprx.htw.de.neeedo I/art﹕ Clamp target GC heap from 67MB to 64MB
```

Could be an emulator issue? Too small heapspace maybe but could also be a memory leak? I opened and reopend the map several times before this happened.

You can force this to happen by opening the map and looking around for a while... zoom in and out, visit different locations. I guess the maptiles are to big for the heap. Can we clear the map cache from time to time?

**Comment by stephanlindauer** [comment]
what i can see when profiling the app:
- it doesnt look like a memory leak
- when there is a lot of scrolling then heap space peaks (which is normal)
- i can't see gc issues or even timeouts on my computer

what i did to semi-fix it was increase the heap size in the manifest.

with this it even seemed to work for stefan. i will close this for now and if we run into more trouble with this we will have to take a deeper look. (but i wouldn't expect us to be able to find workarounds for osmdroid bugs like this one).
