### ISSUE TITLE
Homescreen

### ISSUE THREAD

**Issue by GammaG** [neeedo/neeedo-android#8]
Change layout to "Goldener Schnitt" level - means palce the buttons lower

**Comment by stephanlindauer** [comment]
how much lower? please be more precise.
this should also include adding propper icons to those buttons

**Comment by GammaG** [comment]
I would say about 1-2cm around, I like the icons idear yeah

**Comment by TIIUNDER** [comment]
Maybe colored buttons and also a nice background or background color. Maybe we should create a layout for tablets too

**Comment by TIIUNDER** [comment]
What about this?
![screenshot_2015-07-22-22 08 18-1](https://cloud.githubusercontent.com/assets/1225378/8835984/35bb7050-30be-11e5-860f-2c79bfa709ad.png)

I tried to get the feeling of the webapp using the frame background. Colors for buttons just as idea. Maybe both can be green instead.

**Comment by stephanlindauer** [comment]
love it!

**Comment by stephanlindauer** [comment]
should we also put the icons in there?

**Comment by TIIUNDER** [comment]
Yes, why not, we can try it

**Comment by TIIUNDER** [comment]
How about this?

![screenshot_2015-07-23-21 05 45-1](https://cloud.githubusercontent.com/assets/1225378/8859612/9e9c9976-317e-11e5-9e56-851ea92340e1.png)

**Comment by stephanlindauer** [comment]
nice!
