### ISSUE TITLE
Cant edit or deletemy own offers anymore

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#86]
![screenshot_2015-07-27-22-49-22](https://cloud.githubusercontent.com/assets/1323145/8917344/c616cac2-34b1-11e5-99df-2edb8baca629.png)

**Comment by GammaG** [comment]
what I can see in hipchat it works niw, there were information missing in active user after registration, that's why

**Comment by stephanlindauer** [comment]
yep
