### ISSUE TITLE
utf-8 issue

### ISSUE THREAD

**Issue by stephanlindauer** [neeedo/neeedo-android#89]
E:\workspaces\androidstudio\neeedo-android\app\src\main\java\neeedo\imimaprx\htw\de\neeedo\rest\outpan\GetOutpanByEANAsyncTask.java
Error:(86, 29) error: unmappable character for encoding UTF-8
Error:(86, 39) error: unmappable character for encoding UTF-8
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:app:preDexDebug UP-TO-DATE
:app:dexDebug
:app:processDebugJavaRes UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug

**Comment by GammaG** [comment]
is fixed, added encoding in build.gradle
