### ISSUE TITLE
Zooming to fast in LocationChooser causes App to crash

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#94]
If you zoom very fast and very deep into the OpenStreetMap, the App crashes with following message

`07-29 19:57:41.645    8580-8600/neeedo.imimaprx.htw.de.neeedo A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x78 in tid 8600 (RenderThread)`

Tested on different devices

**Comment by TIIUNDER** [comment]
This only seems to happen on demand location chooser, if you defined the point and distance already and see the distance overlay

**Comment by TIIUNDER** [comment]
You can see it here:

Demands problem with overlay: https://dl.dropboxusercontent.com/u/17564871/20150729_201031.mp4
No problem for offers: https://dl.dropboxusercontent.com/u/17564871/20150729_201135.mp4

I also noticed, at offers location chooser the marker pin is shrinking and growing at each zoom step. In demands location chooser the marker becomes bigger or smaller.

**Comment by TIIUNDER** [comment]
This is really an ugly bug. I tried to draw the polygon only in Map bounding box, but this looks not very nice. Maybe you can check that.

**Comment by stephanlindauer** [comment]
for me it just stops drawing when i zoom in too close.
before it stops drawing its suuuuuuper laggy.
also the new logic says if there are coords outside of the bounding box. dont draw them. so zoomed into the center of the circle you wouldnt have any coordinates to render anymore because all of them would be outside the bounding box. am i right?

**Comment by stephanlindauer** [comment]
how about this: we check the shown area in the bounding box. diagonally and then if that distance is bigger than the actual distance of the circle, we just dont draw the circle anymore.

**Comment by GammaG** [comment]
might be the best solution.

**Comment by stephanlindauer** [comment]
@TIIUNDER 
what do you think? 
will work on that when i get to uni. around 15:00.

**Comment by TIIUNDER** [comment]
@stephanlindauer Yes, this should be easy, tested it yesterday with diagonal length, this should work. I tried to find a better solution, but it's to laggy and does not look very good. So let's do it like you said.

**Comment by TIIUNDER** [comment]
We have still a problem here: Zooming in and after that setting the marker causes the app to crash like before

**Comment by TIIUNDER** [comment]
This does not happen everytime, it happened 3 times now for me on 2 devices, but I'm not able to reproduce this issue
